# fly.toml app configuration file generated for haddock-dingus on 2024-06-26T17:04:11-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'haddock-dingus'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
